### PR TITLE
Check if pass is valid before committing to disable AP and rebooting

### PR DESCRIPTION
**Pull request by ilirb**
Add captive portal thing for iOS and Android
Allow connecting to open APs

### CODE REVIEW

**Comment by ilirb** [comment]
@schollz I'm using Python 2.7 so this is not tested with Python 3 :(

**Comment by schollz** [comment]
Hi @ilirb these look like great changes, thanks! I'll try them out over the weekend and then merge!

**Comment by ilirb** [comment]
Sounds good 👍 

I think we can make it so that if the psk is OK, connect immediately to wifi and disable hostapd without rebooting. Next PR maybe (unless you or someone beats me to it 🏎 )

**Comment by ilirb** [comment]
One more note, RPI can do both hostapd and use wlan as a client. I tried it and was very excited as I was thinking you can serve the connect page while connecting to a client but the excitement went away pretty fast when I learned that both the client and hostapd needs to be on the same channel :doh: anyways...

**Comment by schollz** [comment]
@ilirb Yep there are Python3 errors.

I'm getting:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "startup.py", line 149, in signin
    valid_psk = check_cred(ssid, password)
  File "startup.py", line 87, in check_cred
    f.write(result)
```

This is "bytes" problem with Python2->3.

And also you need `()` around the `print` statements.

You've already done a lot so I don't want you to go through making everything Python3 compatible. If you do want to make it Python3 compatible, I will wait for that. If not I can just merge your stuff into a new branch so I can work on it.

**Comment by ilirb** [comment]
Looks like only the print statements needed change (which I've fixed), I think it should be good now.

**Comment by schollz** [comment]
Okay, awesome! Very very nice work, thanks

**Pull request merged**
